title: 'GPT 4o Table Extractor'
description: 'Analyze tables and forms in your documents using GPT 4o.'
instructions: ''
type: object
documents:
  - selected
properties:
  start_page:
    title: Start page
    type: integer
    description: 'Page number where the table(s) begin'
    default: 1
  end_page:
    title: End page
    type: integer
    description: 'Page number where table(s) end'
    default: 1
  prompt:
    title: Prompt
    type: string
    description: 'GPT 4o prompt to provide for analysis. This field is optional, there is a default prompt.'
  output_format:
    title: 'Output format'
    type: string
    default: csv
    enum:
      - csv
      - json
categories:
  - extraction
  - ai
  - premium
cost:
  price: 2
  amount: 1
  unit: page
version: 2
